### ISSUE TITLE
Can you provide a docker image in docker hub?

### ISSUE THREAD

**Issue by zen-xu** [openbsi/kubesim#3]

**Comment by k82cn** [comment]
I'm ok with that.

/cc @hzxuzhonghu

**Comment by xizhang0919** [comment]
Yes please a docker image. Thanks a lot!

**Comment by Thor-wl** [comment]
Volcano has always docker images in dockerhub. Please try to run `docker search volcano` to get the list of images. You can get the latest image by run `docker pull volcanosh/vc-controller-manager`/`docker pull volcanosh/vc-scheduler`/`volcanosh/vc-webhook-manager`

**Comment by adux6991** [comment]
Hi @k82cn, @Thor-wl, thanks for your work but I think we were requesting for a docker image for **kubesim**, which is used in deployment yaml

https://github.com/volcano-sh/kubesim/blob/d34ac8fe39b44af769c0c4795ccc0e32ac61bb29/example/kubesim-rc.yaml#L44

but does NOT exist in docker hub.

```bash
> docker pull volcanosh/vc-kubesim
Using default tag: latest
Error response from daemon: pull access denied for volcanosh/vc-kubesim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Could you please help?

**Comment by Thor-wl** [comment]
@zen-xu @xizhang0919 @adux6991 docker image for kubesim is already pushed to dockerhub. Please get it with `docker pull volcanosh/vc-kubesim`
